services:
  - type: web
    name: foodsquare-web
    env: python
    region: oregon
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn Foodsquare.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Foodsquare.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 0
      - key: ALLOWED_HOSTS
        value: foodsquare.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: foodsquare-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: apikey
      - key: EMAIL_HOST_PASSWORD
        sync: false  # Add this manually on the Render dashboard

databases:
  - name: foodsquare-db
    plan: free
