name: Publish image to Docker Hub    

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3
    - name: build
      run: |
        docker build . -t vishwajittidke/foodsquare:latest
    - name: publish
      run: |
        docker push vishwajittidke/foodsquare:latest  
